export default [
  { key: 'asp', text: 'ASP', value: 'asp' },
  { key: 'ajax', text: 'AJAX', value: 'ajax' },
  { key: 'java', text: 'Java', value: 'java' },
  { key: 'javascript', text: 'JavaScript', value: 'javascript' },
  { key: 'html5', text: 'HTML5', value: 'html5' },
  { key: 'css3', text: 'CSS3', value: 'css3' },
  { key: 'php', text: 'PHP', value: 'php' },
  { key: 'website design', text: 'Website Design', value: 'website design' },
  { key: 'logo design', text: 'Logo Design', value: 'logo design' },
  { key: 'mobile app development', text: 'Mobile App Development', value: 'mobile app development' },
  { key: 'data entry', text: 'Data Entry', value: 'data entry' },
  { key: 'article writing', text: 'Article Writing', value: 'article writing' },
  { key: 'c', text: 'C', value: 'c' },
  { key: 'c#', text: 'C#', value: 'c#' },
  { key: 'c++', text: 'C++', value: 'c++' },
  { key: 'cobol', text: 'Cobol', value: 'cobol' },
  { key: 'python', text: 'Python', value: 'python' },
];
